### ISSUE TITLE
Remove AZ-down chaos references

### ISSUE THREAD

**Issue by obrienrobert** [bf2fc6cc711aee1a0c2a/kas-fault-tests#11]
## Description
Included in this repository is the Litmus test to replicate an AZ-down: this includes a chaos engine, experiment, SA and `make` commands.

From what I see, this experiment isn't in a working state and is tied to a closed PR to introduce this functionality: [litmuschaos/litmus-go/pull/230](https://github.com/litmuschaos/litmus-go/pull/230). The closed PR highlights the fact that we are not going to re-use the az-down bash script to simulate an az failure: [issuecomment-860627493](https://github.com/litmuschaos/litmus-go/pull/230#issuecomment-860627493).

Can we remove this test and all references to it if it doesn't work? Or maybe we could complete the work in the PR so that we don't have to use the script (it seems to be somewhat close to completion)?

**Comment by obrienrobert** [comment]
@david-martin just wondering if you have any thoughts on this?

**Comment by david-martin** [comment]
Yes, removing makes sense.
It can be retrieved in history if needed

**Comment by obrienrobert** [comment]
Thanks. Created a [PR](https://github.com/bf2fc6cc711aee1a0c2a/kas-fault-tests/pull/12) which removes the test.
